### ISSUE TITLE
add github-action-benchmark

### ISSUE THREAD

**Issue by GopherJ** [casbin/casbin-rs#104]
https://github.com/rhysd/github-action-benchmark looks pretty cool. I put it here in case anyone would like to give a try

**Comment by PsiACE** [comment]
Looks good.

**Comment by PsiACE** [comment]
Done, see #107 .

**Comment by GopherJ** [comment]
hello @PsiACE  It seems that I got some errors:

```
No benchmark result was found in /home/runner/work/casbin-rs/casbin-rs/output.txt. Benchmark output was 'Gnuplot not found, using plotters backend
Benchmarking crate instance of Enforcer
Benchmarking crate instance of Enforcer: Warming up for 3.0000 s
Benchmarking crate instance of Enforcer: Collecting 100 samples in estimated 5.4279 s (30k iterations)
Benchmarking crate instance of Enforcer: Analyzing
crate instance of Enforcer
                        time:   [177.61 us 180.49 us 183.75 us]
Found 8 outliers among 100 measurements (8.00%)
  2 (2.00%) low severe
  1 (1.00%) low mild
  1 (1.00%) high mild
  4 (4.00%) high severe

Benchmarking enforces two permissions
Benchmarking enforces two permissions: Warming up for 3.0000 s
Benchmarking enforces two permissions: Collecting 100 samples in estimated 6.0250 s (10k iterations)
Benchmarking enforces two permissions: Analyzing
enforces two permissions
                        time:   [600.69 us 611.44 us 623.17 us]
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild

Benchmarking adds permission for user MemoryAdapter
Benchmarking adds permission for user MemoryAdapter: Warming up for 3.0000 s
Benchmarking adds permission for user MemoryAdapter: Collecting 100 samples in estimated 5.0032 s (6.9M iterations)
Benchmarking adds permission for user MemoryAdapter: Analyzing
adds permission for user MemoryAdapter
                        time:   [720.50 ns 730.04 ns 740.13 ns]
Found 4 outliers among 100 measurements (4.00%)
  2 (2.00%) high mild
  2 (2.00%) high severe

Benchmarking crate instance of FileAdapter
Benchmarking crate instance of FileAdapter: Warming up for 3.0000 s
Benchmarking crate instance of FileAdapter: Collecting 100 samples in estimated 5.0000 s (12297829157B iterations)
Benchmarking crate instance of FileAdapter: Analyzing
crate instance of FileAdapter
                        time:   [0.0000 ps 0.0000 ps 0.0000 ps]
Found 7 outliers among 100 measurements (7.00%)
  3 (3.00%) high mild
  4 (4.00%) high severe

```

**Comment by GopherJ** [comment]
Do you have any idea on this? Is it because that basically it'll need two commits for comparing and the first PR will not be able to find previous result?

**Comment by GopherJ** [comment]
```
No benchmark result was found in /home/runner/work/casbin-rs/casbin-rs/output.txt. Benchmark output was 'Gnuplot not found, using plotters backend
```
will this be the cause?

**Comment by GopherJ** [comment]
Another difference is that in your loge repo, you are using `test::Bencher` and in casbin-rs we are using criterion

**Comment by GopherJ** [comment]
Ok seems it doesn't support criterion results. Let's switch back to `test::Bencher`

**Comment by PsiACE** [comment]
`error: bench failed`, so we need fix bench first.

**Comment by PsiACE** [comment]
```
thread 'main' panicked at 'index out of bounds: the len is 500 but the index is 18446744073709551615', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.1/src/plot/plotters_backend/distributions.rs:31:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: bench failed
```

**Comment by PsiACE** [comment]
> Ok seems it doesn't support criterion results. Let's switch back to `test::Bencher`
> 
> Related: [rhysd/github-action-benchmark#8](https://github.com/rhysd/github-action-benchmark/issues/8)

Perhaps you're right. But first of all, it should be noted that the reason for the final failure of CI is that there is no output.txt, which is caused by the failure of the bench.

**Comment by PsiACE** [comment]
Good example with criterion & github-action-benchmark -> https://github.com/clap-rs/clap/

**Comment by GopherJ** [comment]
@PsiACE how to reproduce this?
```
thread 'main' panicked at 'index out of bounds: the len is 500 but the index is 18446744073709551615', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.1/src/plot/plotters_backend/distributions.rs:31:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: bench failed
```

**Comment by PsiACE** [comment]
I don't know. Now the computer is not at hand.

Find it at the `Run benchmark` at https://github.com/casbin/casbin-rs/runs/581016543?check_suite_focus=true

**Comment by pksunkara** [comment]
It does support with my fork of criterion. You can check it out on https://github.com/clap-rs/clap. We setup PR benchmarking.

**Comment by GopherJ** [comment]
thanks to make it simple we switched back to test::Bencher
